name: Deploy Documentation

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-documentation:
    name: Build and Deploy Documentation
    runs-on: macos-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Build DocC
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation \
            --target LoggerLibrary \
            --output-path ./docs \
            --transform-for-static-hosting \
            --hosting-base-path LoggerLibrary

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          cname: false
